### ISSUE TITLE
Husky的训练过程？

### ISSUE THREAD

**Issue by WHB139426** [OpenGVLab/InternChat#3]
论文中没有说明Husky的训练过程，只说了是三阶段的训练？可以详细说一下这三阶段训练的过程与用到的数据集吗

**Comment by wofmanaf** [comment]
stage1：图像文本对齐，更新language_project, 数据集为cc3m以及recaption的laion数据，stage2: 精细微调，更新 language_project, 用到的数据为[llava_instruct_150k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/llava_instruct_150k.json). stage3: 针对特定场景做了进一步微调

**Comment by WHB139426** [comment]
明白，多谢回复
